<html>
    <head>
        <title>Shopping Hall</title>
        <script language="javascript">
            function goMyCart() {
                window.location.href = "/shopping/showcart";
            }
        </script>
    </head>

    <body>
        <h1>Welcome to Shopping Hall, <?php echo $this->loginuser['name']?></h1>
        <table width="700px">
            <tr>
                <td>Book Name</td>
                <td>Price</td>
                <td>Publishing House</td>
                <td>Buy</td>
            </tr>
            <?php foreach ($this->books as $book) {?>
            <tr>
                <td><?php echo $book['name']?></td>
                <td><?php echo $book['price']?></td>
                <td><?php echo $book['publishHouse']?></td>
                <td><a href='/shopping/addproduct?bookid=<?php echo $book['id']?>'>Buy</a></td>
            </tr>
            <?php }?> 
            <tr>
                <td colspan="4"><input type="button" onclick="goMyCart();" value="check mycart"></td>
            </tr>

        </table>
    </body>
</html>