<html>
    <head>
        <title>Login</title>
    </head>
    <body>
        <h1>login</h1>
        <form action="/login/login" method="post">
            <table>
                <tr>
                    <td>userid</td>
                    <td><input type="text" name="id"/></td>
                </tr>
                <tr>
                    <td>userpassword</td>
                    <td><input type="password" name="pwd"/></td>
                </tr>
                <tr>
                    <td><input type="submit" value="Login"/></td>
                    <td><input type="reset" value="reset"/></td>
                </tr>
            </table>
        </form>
        <?php echo $this->err?>
    </body>
</html>